#
###################################
# Site wide configuration
####################################
#
title: Mohammed Ibrahim Khan
email: ibrahimkhan7777@gmail.com
description: Machine learning, Deep learning, CNN, CV
url: # the base hostname & protocol for your site
keywords: ["blog", "ml"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          India
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Mohammed Ibrahim Khan
  avatar: 
  job: 
  bio: "Machine learning, Deep learning, CNN, CV"
  email: ibrahimkhan7777@gmail.com
  disqus-shortname:
  twitter: ibrahimKkhn
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: exekudos
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
